import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useAuthState } from "react-firebase-hooks/auth";
import PageContentLayout from "../components/Layout/PageContent";
import { auth } from "../firebase/clientApp";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [user, loadingUser] = useAuthState(auth);
  const [loaing, setLoading] = useState(false);

  const buildUserHomeFeed = () => {};
  const buildNoUserHomeFeed = () => {};
  const getUserPostVotes = () => {};

  useEffect(() => {
    if (!user && !loadingUser) {
      buildNoUserHomeFeed();
    }
  }, [user, loadingUser]);

  return (
    <div>
      <Head>
        <title>Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageContentLayout>
        <></>
        <></>
      </PageContentLayout>
    </div>
  );
};

export default Home;
